In [ ]:
'''Exploratory data analysis'''
'''Understanding the dataset to explore how the data is present in  a database and if there is a need of createing some aggregated tables that can help with:
.vendor selection for profitability
.product pricing optimization'''

In [1]:
import pandas as pd
import sqlite3

In [ ]:
#creating database connection
conn = sqlite3.connect('my_database.db')

In [3]:
#checking tables present in the database
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn)
tables

              name
0             begi
1             end_
2             purc
3             sale
4  begin_inventory
5  purchase_prices
6   vendor_invoice

In [5]:
pd.read_sql("select count(*) from begin_inventory",conn)

   count(*)
0         0